### ISSUE TITLE
Create step file of board to enable case design

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_ESC#8]
@runger1101001 when you have time could you export a .step file of the ESC please so we can design the 3D print case to fit.

Ref
https://github.com/rosmo-robot/Rosmo_3D/issues/2

**Comment by runger1101001** [comment]
[Rosmo_ESC.step.zip](https://github.com/rosmo-robot/Rosmo_ESC/files/7804330/Rosmo_ESC.step.zip)

The STEP export only includes the ports and a few components, all the other components don't get exported... but this should give the outer dimensions, and the since the ports are on there... note the terminal blocks are not the right ones...

**Comment by samuk** [comment]
Nice one, thanks. Should be OK for the case design.
